// Generated by gir (https://github.com/gtk-rs/gir @ ee0e85140a6f)
// from ../gir-files (@ 8be196040235)
// DO NOT EDIT

fn main() {
  if std::env::var("DOCS_RS").is_ok() {
    // prevent linking libraries to avoid documentation failure
    return;
  }

  if let Err(s) = system_deps::Config::new().probe() {
    println!("cargo:warning={s}");
    std::process::exit(1);
  }
}
