// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files (https://github.com/gtk-rs/gir-files.git)
// DO NOT EDIT

use glib::translate::*;

glib::wrapper! {
    #[derive(Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
    pub struct StringRef(Shared<ffi::JSStringRef>);

    match fn {
        ref => |ptr| ffi::JSStringRetain(*ptr),
        unref => |ptr| ffi::JSStringRelease(*ptr),
    }
}

impl StringRef {
    #[doc(alias = "JSStringGetMaximumUTF8CStringSize")]
    pub fn get_maximum_utf8_cstring_size(&self) -> usize {
        unsafe {
            ffi::JSStringGetMaximumUTF8CStringSize(*self.to_glib_none().0)
        }
    }

    //#[doc(alias = "JSStringGetUTF8CString")]
    //pub fn GetUTF8CStringJSStringGetUTF8CString(&self, buffer: /*Unimplemented*/glib::GString, buffer_size: usize) -> usize {
    //    unsafe { TODO: call ffi:JSStringGetUTF8CString() }
    //}
}
