[options]
library = "JavaScriptCore"
version = "4.0"
target_path = "."
min_cfg_version = "2.32"
work_mode = "sys"
girs_directories = [ "../gir-files/" ]

external_libraries = [
    "GLib",
    "GObject",
]
